[package]
name = "rust-actix"
version = "0.1.0"
authors = ["Icebob <mereg.norbert@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
serde = "1.0.118"
reqwest = "0.10.10"
