version: "3.8"

services:
  sidecar:
    image: sidecar-demo-main
    build:
      context: ../../
      dockerfile: Dockerfile-alpine
    environment:
      SIDECAR_PORT: 5103
      TRANSPORTER: nats://nats:4222
    depends_on:
      - nats
    networks:
      - internal
      - external
    restart: always

  nats:
    image: nats
    ports:
      - "4222:4222"
    networks:
      - external
    restart: always

  ballerina-demo:
    image: sidecar-demo-ballerina
    build:
      context: ./ballerina
    environment:
      SIDECAR_ADDRESS: http://sidecar:5103
    depends_on:
      - sidecar
    networks:
      - internal
    restart: always

  deno-demo:
    image: sidecar-demo-deno
    build:
      context: ./deno-oak
    environment:
      SIDECAR_ADDRESS: http://sidecar:5103
    depends_on:
      - sidecar
    networks:
      - internal
    restart: always

  go-demo:
    image: sidecar-demo-go
    build:
      context: ./go-fiber
    environment:
      SIDECAR_ADDRESS: http://sidecar:5103
    depends_on:
      - sidecar
    networks:
      - internal
    restart: always

  php-demo:
    image: sidecar-demo-php
    build:
      context: ./php-mark
    environment:
      SIDECAR_ADDRESS: http://sidecar:5103
    depends_on:
      - sidecar
    networks:
      - internal
    restart: always

  python-demo:
    image: sidecar-demo-python
    build:
      context: ./python-flask
    environment:
      SIDECAR_ADDRESS: http://sidecar:5103
    depends_on:
      - sidecar
    networks:
      - internal
    restart: always

  ruby-demo:
    image: sidecar-demo-ruby
    build:
      context: ./ruby-sinatra
    environment:
      SIDECAR_ADDRESS: http://sidecar:5103
    depends_on:
      - sidecar
    networks:
      - internal
    restart: always

  rust-demo:
    image: sidecar-demo-rust
    build:
      context: ./rust-actix
    environment:
      SIDECAR_ADDRESS: http://sidecar:5103
    depends_on:
      - sidecar
    networks:
      - internal
    restart: always

  swift-demo:
    image: sidecar-demo-swift
    build:
      context: ./swift-perfect
    environment:
      SIDECAR_ADDRESS: http://sidecar:5103
    depends_on:
      - sidecar
    networks:
      - internal
    restart: always

  crystal-demo:
    image: sidecar-demo-crystal
    build:
      context: ./crystal-kemal
    environment:
      SIDECAR_ADDRESS: http://sidecar:5103
    depends_on:
      - sidecar
    networks:
      - internal
    restart: always

networks:
  internal: {}
  external: {}
