name: Integration Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci --silent

    - name: Run tests
      run: npm run test

    #- name: Start containers
    #  run: docker-compose up -d
    #  working-directory: ./test

    #- name: Sleeping 30 secs
    #  run: sleep 30

    #- name: Check containers
    #  run: docker-compose ps
    #  working-directory: ./test

    #- name: Check logs
    #  run: docker-compose logs
    #  working-directory: ./test

    #- name: Run integration tests
    #  run: npm test

    #- name: Stop containers
    #  run: docker-compose down -v
    #  working-directory: ./test
